### PR TITLE
Added a new field for exposure time, and time needed to complete field

### PR DESCRIPTION
**Pull request by EricPell**

### CODE REVIEW

**Comment by albireox** [comment]
I think it's ok to add this information here but I'm a bit confused about the names. It seems to me that `exptime_tot` should be the total exposed time (e.g. 8100s) and `exptime_point` should be the exposure time of a single pointing.

Another alternative is to simply indicate something like `n_exposures` to indicate how many exposures to take per pointing in that target.

**Comment by EricPell** [comment]
Niv and I also talked and we agree. But we need a third field which is min_n_exposures for a visit.

**Comment by albireox** [comment]
This looks good to me.

**Comment by EricPell** [comment]
Thanks Jose,

Me and Niv were trying to make some faster progress, so we forked things. We handled all the names. We’ll merge soon.

Sent from Mail for Windows 10

**Comment by albireox** [comment]
Sounds good. I'm also working on this today and hope to have a simulation with multiple exposures ready soon. One question about the fields you added. For some of the extragalactic targets there is

```
    exptime_total: 3600
    n_exposures: 1
    min_exposures: 1
```

That seems inconsistent. Should I pay attention to `exptime_total` or to `n_exposures`? What's the use of `min_exposures`? Are these the number of exposures that need to be taken together, back-to-back? If so I'd prefer to call them something like `n_exposures_visit` or similar.

**Comment by EricPell** [comment]
Oh, we have multiple expososure times working.

Here: 
https://github.com/EricPell/lvmcore

Everything in the forked target file is fully implemented

Sent from Mail for Windows 10

**Comment by EricPell** [comment]
I guess I should have just emailed


M31:
    coords: [[10.576, 41.244], [11.12, 41.19],
             [11.95, 42.195], [11.42, 42.26]]
    region_type: polygon
    frame: icrs
    priority: 3
    observatory: APO
    telescope: LVM-1m
    max_airmass: 1.75
    exptime: 1200
    n_exposures: 9
    min_exposures: 3
    min_moon_dist: 25
    max_lunation: 0.2
    overhead: 1.1


Sent from Mail for Windows 10

**Comment by albireox** [comment]
Ok, those seem enough changes that you're probably planning to implement some significant modifications. I'll wait until you merge your changes.

**Comment by EricPell** [comment]
Yeah, we’ve made some pretty serious changes. Me and Niv had a busy week. We spend a few days working on it.

Sent from Mail for Windows 10

**Pull request merged**
